spring:
  application:
    name: edge-server
server:
  port: 5566

zuul:
  routes:
    api-account1:
      path: /account/**
      url: http://localhost:7000/ # 用 url 指出欲轉導的位置
    ribbon:
      path: /ribbon/**
      serviceId: ribbon # 用 eureka 的 Application name 指出欲轉導的對象

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

security:
  user:
    password: user  # 直接登錄的密碼
  ignored: / #略過 security 保護的路徑
  sessions: never   # session策略

  oauth2:
    sso:
      login-path: /login   # 登錄路徑
    client:
      client-id: 123456789-abcdefghijklmnopq0oenpkqrl4u.apps.googleusercontent.com  # your client id
      client-secret: VeRySiMpLeSaMpLe_DaGuy4john # your client secret
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      scope: https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile
      client-authentication-scheme: form
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: false
