server:
  port: 1111

eureka:
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/