server:
  port: 1201

management:
  context-path: /admin
  security:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        native: # Classpath and file-based solution
          search-locations: classpath:config/ribbon,
                          classpath:config/inlight #file:config/inlight
        db:
          applications:
            - application: inlight #name of application
              table: app-default  #name of db table
              profile: profile    #name of profile column
              property: property  #name of property column
              value: value        #name of value column
            - application: ribbon
              table: app-default
              profile: profile
              property: property
              value: value
        git: # Remote base solution
          uri: https://github.com/goldenchen-insnergy/config-repo

  datasource:
    url: jdbc:postgresql://xxx.xxx.xxx.xxx:xxxx/
    username: xxxx
    password: xxxx
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true